version: 2

sources:
  - name: raw_data_circle
    description: raw data circle sportswear from le wagon
    tables:
      - name: raw_cc_sales
        description: sales of products
      - name: raw_cc_stock
        description: stock of products
        tests:
          - unique:
              column_name: "(model || '_' || color || '_' || size)"